// bigwig datafetcher
// bar mark
// orange color
const excitatory_neurons = {
  id: "3486b662-d79a-4c14-936b-b62d2d0e9205",
  siblingIds: ["3486b662-d79a-4c14-936b-b62d2d0e9205"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Excitatory neurons",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      axis: "none",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/ExcitatoryNeurons-insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "Excitatory neurons",
    mark: "bar",
    color: { value: "#F29B67" },
    id: "3486b662-d79a-4c14-936b-b62d2d0e9205",
    overlayOnPreviousTrack: false,
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const inhibitory = {
  id: "c212d607-2bd4-4385-a22c-210279eca4c2",
  siblingIds: ["c212d607-2bd4-4385-a22c-210279eca4c2"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Inhibitory neurons",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/InhibitoryNeurons-insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "Inhibitory neurons",
    mark: "bar",
    color: { value: "#3DC491" },
    id: "c212d607-2bd4-4385-a22c-210279eca4c2",
    _renderingId: "dbd07f0e-f538-4f2b-a433-9b157f3c903d",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const dopaminergic = {
  id: "7bce13e0-275c-484d-a9e4-eb679b3f1c25",
  siblingIds: ["7bce13e0-275c-484d-a9e4-eb679b3f1c25"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Dopaminergic neurons",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/DopaNeurons_Cluster10_AllFrags_projSUNI2_insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "Dopaminergic neurons",
    mark: "bar",
    color: { value: "#565C8B" },
    id: "7bce13e0-275c-484d-a9e4-eb679b3f1c25",
    _renderingId: "d9370816-5563-4556-8f3b-ac790ff29023",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const microglia = {
  id: "918e8830-dfa6-4616-9e72-5cfcfd278fde",
  siblingIds: ["918e8830-dfa6-4616-9e72-5cfcfd278fde"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Microglia",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/Microglia-insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "Microglia",
    mark: "bar",
    color: { value: "#77C0FA" },
    id: "918e8830-dfa6-4616-9e72-5cfcfd278fde",
    _renderingId: "2907c826-4560-4b70-9b63-a8a84bfceb48",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const oligodendrocytes = {
  id: "4c927f23-6e29-4b85-bbd2-41a05fc0c927",
  siblingIds: ["4c927f23-6e29-4b85-bbd2-41a05fc0c927"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Oligodendrocytes",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/Oligodendrocytes-insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "Oligodendrocytes",
    mark: "bar",
    color: { value: "#9B46E5" },
    id: "4c927f23-6e29-4b85-bbd2-41a05fc0c927",
    _renderingId: "7e9f1c53-0719-406c-97a0-cc33de4ff1e4",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const astrocytes = {
  id: "5251ab47-ff2f-40a4-8bdb-ad0d1a5a1365",
  siblingIds: ["5251ab47-ff2f-40a4-8bdb-ad0d1a5a1365"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Astrocytes",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/Astrocytes-insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "Astrocytes",
    mark: "bar",
    color: { value: "#D73636" },
    id: "5251ab47-ff2f-40a4-8bdb-ad0d1a5a1365",
    _renderingId: "ecb2c970-7425-498b-9809-c01484647d83",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const OPCs = {
  id: "9da56b88-2a59-475a-a167-885100fa53a9",
  siblingIds: ["9da56b88-2a59-475a-a167-885100fa53a9"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "OPCs",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "position",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
    },
    y: {
      field: "peak",
      type: "quantitative",
      axis: "right",
    },
    style: { outline: "#20102F" },
    width: 400,
    height: 40,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    data: {
      url: "https://s3.amazonaws.com/gosling-lang.org/data/OPCs-insertions_bin100_RIPnorm.bw",
      type: "bigwig",
      column: "position",
      value: "peak",
    },
    title: "OPCs",
    mark: "bar",
    color: { value: "#E38ADC" },
    id: "9da56b88-2a59-475a-a167-885100fa53a9",
    _renderingId: "0f0edfb0-74cd-4746-9e1f-8e40e1089601",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

export const gene_annotation = {
  id: "24feadcc-7b65-43a7-a45c-2df65405ec8c",
  siblingIds: ["24feadcc-7b65-43a7-a45c-2df65405ec8c"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Genes",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    title: "Genes",
    data: {
      url: "https://server.gosling-lang.org/api/v1/tileset_info/?d=gene-annotation",
      type: "beddb",
      genomicFields: [
        { index: 1, name: "start" },
        { index: 2, name: "end" },
      ],
      valueFields: [
        { index: 5, name: "strand", type: "nominal" },
        { index: 3, name: "name", type: "nominal" },
      ],
      exonIntervalFields: [
        { index: 12, name: "start" },
        { index: 13, name: "end" },
      ],
    },
    style: { outline: "#20102F" },
    row: {
      field: "strand",
      type: "nominal",
      domain: ["+", "-"],
    },
    color: {
      field: "strand",
      type: "nominal",
      domain: ["+", "-"],
      range: ["#012DB8", "#BE1E2C"],
    },
    visibility: [
      {
        operation: "less-than",
        measure: "width",
        threshold: "|xe-x|",
        transitionPadding: 10,
        target: "mark",
      },
    ],
    width: 400,
    height: 110,
    _overlay: [
      {
        dataTransform: [
          {
            type: "filter",
            field: "type",
            oneOf: ["gene"],
          },
          { type: "filter", field: "strand", oneOf: ["+"] },
        ],
        mark: "text",
        text: { field: "name", type: "nominal" },
        x: {
          field: "start",
          type: "genomic",
          domain: {
            chromosome: "chr3",
            interval: [52168000, 52890000],
          },
          axis: "top",
        },
        size: { value: 8 },
        xe: { field: "end", type: "genomic" },
        style: {
          outline: "#20102F",
          textFontSize: 8,
          dy: -12,
        },
      },
      {
        dataTransform: [
          {
            type: "filter",
            field: "type",
            oneOf: ["gene"],
          },
          { type: "filter", field: "strand", oneOf: ["-"] },
        ],
        mark: "text",
        text: { field: "name", type: "nominal" },
        x: {
          field: "start",
          type: "genomic",
          domain: {
            chromosome: "chr3",
            interval: [52168000, 52890000],
          },
          axis: "top",
        },
        xe: { field: "end", type: "genomic" },
        size: { value: 8 },
        style: {
          outline: "#20102F",
          textFontSize: 8,
          dy: 10,
        },
      },
      {
        dataTransform: [
          {
            type: "filter",
            field: "type",
            oneOf: ["gene"],
          },
          { type: "filter", field: "strand", oneOf: ["+"] },
        ],
        mark: "rect",
        x: {
          field: "end",
          type: "genomic",
          domain: {
            chromosome: "chr3",
            interval: [52168000, 52890000],
          },
          axis: "top",
        },
        size: { value: 7 },
        style: { outline: "#20102F" },
      },
      {
        dataTransform: [
          {
            type: "filter",
            field: "type",
            oneOf: ["gene"],
          },
          { type: "filter", field: "strand", oneOf: ["-"] },
        ],
        mark: "rect",
        x: {
          field: "start",
          type: "genomic",
          domain: {
            chromosome: "chr3",
            interval: [52168000, 52890000],
          },
          axis: "top",
        },
        size: { value: 7 },
        style: { outline: "#20102F" },
      },
      {
        dataTransform: [{ type: "filter", field: "type", oneOf: ["exon"] }],
        mark: "rect",
        x: {
          field: "start",
          type: "genomic",
          domain: {
            chromosome: "chr3",
            interval: [52168000, 52890000],
          },
          axis: "top",
        },
        xe: { field: "end", type: "genomic" },
        size: { value: 14 },
        style: { outline: "#20102F" },
      },
      {
        dataTransform: [{ type: "filter", field: "type", oneOf: ["gene"] }],
        mark: "rule",
        x: {
          field: "start",
          type: "genomic",
          domain: {
            chromosome: "chr3",
            interval: [52168000, 52890000],
          },
          axis: "top",
        },
        xe: { field: "end", type: "genomic" },
        strokeWidth: { value: 3 },
        style: { outline: "#20102F" },
      },
    ],
    id: "24feadcc-7b65-43a7-a45c-2df65405ec8c",
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    overlayOnPreviousTrack: false,
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const plac_seq1 = {
  id: "f7689c8c-3ca1-4def-9990-c199dd46ee2b",
  siblingIds: ["f7689c8c-3ca1-4def-9990-c199dd46ee2b"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "PLAC-seq (H3K4me3) Nott et al.",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "start",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
      axis: "top",
    },
    y: { flip: true },
    style: { outline: "#20102F" },
    width: 400,
    height: 90,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    title: "PLAC-seq (H3K4me3) Nott et al.",
    data: {
      url: "https://server.gosling-lang.org/api/v1/tileset_info/?d=oligodendrocyte-plac-seq-bedpe",
      type: "beddb",
      genomicFields: [
        { name: "start", index: 1 },
        { name: "end", index: 2 },
      ],
    },
    mark: "withinLink",
    xe: { field: "end", type: "genomic" },
    strokeWidth: { value: 1 },
    color: { value: "none" },
    stroke: { value: "#F97E2A" },
    opacity: { value: 0.1 },
    overlayOnPreviousTrack: false,
    id: "f7689c8c-3ca1-4def-9990-c199dd46ee2b",
    _renderingId: "7e025b68-7f5e-4030-86d4-e16c81e64521",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const plac_seq2 = {
  id: "88adbace-ab3d-4dba-9ecb-54d212db2618",
  siblingIds: ["88adbace-ab3d-4dba-9ecb-54d212db2618"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "Microglia.5k_interactions_ucsc_genome_browser.inter.bb",
  labelPosition: "none",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "start",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
      axis: "top",
    },
    y: { flip: true },
    style: { outline: "#20102F" },
    width: 400,
    height: 90,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    title: "",
    data: {
      url: "https://server.gosling-lang.org/api/v1/tileset_info/?d=microglia-plac-seq-bedpe",
      type: "beddb",
      genomicFields: [
        { name: "start", index: 1 },
        { name: "end", index: 2 },
      ],
    },
    mark: "withinLink",
    xe: { field: "end", type: "genomic" },
    strokeWidth: { value: 1 },
    color: { value: "none" },
    stroke: { value: "#50ADF9" },
    opacity: { value: 0.1 },
    overlayOnPreviousTrack: true,
    id: "88adbace-ab3d-4dba-9ecb-54d212db2618",
    _renderingId: "419c95e2-3ccd-4d53-98b8-34248f1ca298",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

const plac_seq3 = {
  id: "a03868c2-9e8a-4354-8c50-9e35967d98df",
  siblingIds: ["a03868c2-9e8a-4354-8c50-9e35967d98df"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "NeuN.5k_interactions_ucsc_genome_browser.inter.bb",
  labelPosition: "none",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    xDomain: {
      chromosome: "chr3",
      interval: [52168000, 52890000],
    },
    linkingId: "detail",
    x: {
      field: "start",
      type: "genomic",
      domain: {
        chromosome: "chr3",
        interval: [52168000, 52890000],
      },
      axis: "top",
    },
    y: { flip: true },
    style: { outline: "#20102F" },
    width: 400,
    height: 90,
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    centerRadius: 0.3,
    xOffset: 0,
    yOffset: 0,
    title: "",
    data: {
      url: "https://server.gosling-lang.org/api/v1/tileset_info/?d=neuron-plac-seq-bedpe",
      type: "beddb",
      genomicFields: [
        { name: "start", index: 1 },
        { name: "end", index: 2 },
      ],
    },
    mark: "withinLink",
    xe: { field: "end", type: "genomic" },
    strokeWidth: { value: 1 },
    color: { value: "none" },
    stroke: { value: "#7B0EDC" },
    opacity: { value: 0.1 },
    overlayOnPreviousTrack: true,
    id: "a03868c2-9e8a-4354-8c50-9e35967d98df",
    _renderingId: "4780eefe-f6af-4c3a-94e4-7e4cd18c2a02",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

export const ideogram = {
  id: "23264a70-5730-4979-8a75-668e1b55bddd",
  siblingIds: ["23264a70-5730-4979-8a75-668e1b55bddd"],
  showMousePosition: false,
  mousePositionColor: "#000000",
  name: "chr3",
  labelPosition: "topLeft",
  labelShowResolution: false,
  labelColor: "black",
  labelBackgroundColor: "white",
  labelBackgroundOpacity: 0.5,
  labelTextOpacity: 1,
  labelLeftMargin: 1,
  labelTopMargin: 1,
  labelRightMargin: 0,
  labelBottomMargin: 0,
  backgroundColor: "transparent",
  spec: {
    title: "chr3",
    data: {
      url: "https://raw.githubusercontent.com/sehilyi/gemini-datasets/master/data/cytogenetic_band.csv",
      type: "csv",
      chromosomeField: "Chr.",
      genomicFields: [
        "ISCN_start",
        "ISCN_stop",
        "Basepair_start",
        "Basepair_stop",
      ],
    },
    x: {
      field: "Basepair_start",
      type: "genomic",
      axis: "none",
      domain: { chromosome: "chr3" },
    },
    xe: { field: "Basepair_stop", type: "genomic" },
    stroke: { value: "black" },
    strokeWidth: { value: 1 },
    style: { outlineWidth: 0 },
    width: 400,
    height: 55,
    _overlay: [
      {
        mark: "rect",
        dataTransform: [
          {
            type: "filter",
            field: "Stain",
            oneOf: ["acen-1", "acen-2"],
            not: true,
          },
        ],
        color: {
          field: "Density",
          type: "nominal",
          domain: ["", "25", "50", "75", "100"],
          range: ["white", "#D9D9D9", "#979797", "#636363", "black"],
        },
        size: { value: 20 },
        style: { outlineWidth: 0 },
      },
      {
        mark: "rect",
        dataTransform: [
          {
            type: "filter",
            field: "Stain",
            oneOf: ["gvar"],
          },
        ],
        color: { value: "#A0A0F2" },
        size: { value: 20 },
        style: { outlineWidth: 0 },
      },
      {
        mark: "triangleRight",
        dataTransform: [
          {
            type: "filter",
            field: "Stain",
            oneOf: ["acen-1"],
          },
        ],
        color: { value: "#B40101" },
        size: { value: 20 },
        style: { outlineWidth: 0 },
      },
      {
        mark: "triangleLeft",
        dataTransform: [
          {
            type: "filter",
            field: "Stain",
            oneOf: ["acen-2"],
          },
        ],
        color: { value: "#B40101" },
        size: { value: 20 },
        style: { outlineWidth: 0 },
      },
      {
        mark: "brush",
        x: { axis: "top" },
        color: { value: "red" },
        opacity: { value: 0.3 },
        strokeWidth: { value: 1 },
        stroke: { value: "red" },
        style: { outlineWidth: 0 },
      },
    ],
    id: "23264a70-5730-4979-8a75-668e1b55bddd",
    assembly: "hg38",
    layout: "linear",
    orientation: "horizontal",
    static: false,
    zoomLimits: [1, null],
    overlayOnPreviousTrack: false,
    _renderingId: "9778a52d-bea3-4ab6-a11d-9a8bb73443a2",
  },
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
};

export const axisTrack = {
  id: "62c6e5ca-1713-4d0d-afb0-cfcc00b2c703-top-axis",
  layout: "linear",
  innerRadius: null,
  width: 400,
  height: 70,
  theme: {
    base: "light",
    root: {
      background: "white",
      titleColor: "black",
      titleBackgroundColor: "transparent",
      titleFontSize: 18,
      titleFontFamily: "Arial",
      titleAlign: "left",
      titleFontWeight: "bold",
      subtitleColor: "gray",
      subtitleBackgroundColor: "transparent",
      subtitleFontSize: 16,
      subtitleFontFamily: "Arial",
      subtitleFontWeight: "normal",
      subtitleAlign: "left",
      showMousePosition: true,
      mousePositionColor: "#000000",
    },
    track: {
      background: "transparent",
      alternatingBackground: "transparent",
      titleColor: "black",
      titleBackground: "white",
      titleFontSize: 24,
      titleAlign: "left",
      outline: "black",
      outlineWidth: 1,
    },
    legend: {
      position: "top",
      background: "white",
      backgroundOpacity: 0.7,
      labelColor: "black",
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      backgroundStroke: "#DBDBDB",
      tickColor: "black",
    },
    axis: {
      tickColor: "black",
      labelColor: "black",
      labelMargin: 5,
      labelExcludeChrPrefix: false,
      labelFontSize: 12,
      labelFontWeight: "normal",
      labelFontFamily: "Arial",
      baselineColor: "black",
      gridColor: "#E3E3E3",
      gridStrokeWidth: 1,
      gridStrokeType: "solid",
      gridStrokeDash: [4, 4],
    },
    markCommon: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    point: {
      color: "#E79F00",
      size: 3,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rect: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    triangle: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    area: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    line: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    bar: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    rule: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    link: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
    text: {
      color: "#E79F00",
      size: 1,
      stroke: "black",
      strokeWidth: 0,
      opacity: 1,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
      textAnchor: "middle",
      textFontWeight: "normal",
    },
    brush: {
      color: "gray",
      size: 1,
      stroke: "black",
      strokeWidth: 1,
      opacity: 0.3,
      nominalColorRange: [
        "#E79F00",
        "#029F73",
        "#0072B2",
        "#CB7AA7",
        "#D45E00",
        "#57B4E9",
        "#EFE441",
      ],
      quantitativeSizeRange: [2, 6],
    },
  },
  assembly: "hg38",
  stroke: "transparent",
  color: "black",
  labelMargin: 5,
  excludeChrPrefix: false,
  fontSize: 12,
  fontFamily: "Arial",
  fontWeight: "normal",
  tickColor: "black",
  tickFormat: "plain",
  tickPositions: "ends",
  reverseOrientation: false,
};

export const bigwigTracks = [
  excitatory_neurons,
  inhibitory,
  dopaminergic,
  microglia,
  oligodendrocytes,
  astrocytes,
  OPCs,
];

export const placTracks = [plac_seq1, plac_seq2, plac_seq3];
